// AUTO-GENERATED by scripts/generate-mock.mjs — do not edit by hand.
// Seed: 42. Re-run: node scripts/generate-mock.mjs
// Faker lives only in the generator; this file is pure app-core subset data.

import { asciiBytes } from "@native-sdk/core";
import type { Project } from "./types.ts";

export const MOCK_SEED = 42 as const;

export const MOCK_PROJECTS: readonly Project[] = [
  {
    id: 1,
    name: asciiBytes("Wall-E"),
    path: asciiBytes("/Users/demo/Project/Wall-E"),
    description: asciiBytes("Reduced methodical capability"),
    threads: [
      {
        id: 2,
        title: asciiBytes("Refactor driver"),
        status: "idle",
        statusLabel: asciiBytes("Idle"),
        messages: [
      {
        id: 3,
        role: "user",
        isUser: true,
        content: asciiBytes("Fix the online bug in roughly.boz"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 6,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Aer contego ancilla urbanus qui comptus adversus colo communis. Repellendus valens demens animadverto summisse temptatio laudantium tepidus. Eos cursus acies amita addo repellat.\nDolor venustas carus cunae temeritas. Aestus clam arx vetus. Recusandae ut thymbra audentia vapulus fugit timor vel cometes."),
        toolCount: 2,
        tools: [
      {
        id: 4,
        name: asciiBytes("search_replace"),
        state: "requires_action",
        inputSummary: asciiBytes("search_replace utilized_wherever.odt"),
        outputSummary: asciiBytes(""),
        errorText: asciiBytes(""),
      },
      {
        id: 5,
        name: asciiBytes("search_replace"),
        state: "requires_action",
        inputSummary: asciiBytes("search_replace thoughtfully.bmp"),
        outputSummary: asciiBytes(""),
        errorText: asciiBytes(""),
      }
        ] as const,
      }
        ] as const,
        fileChanges: [
      {
        id: 7,
        path: asciiBytes("src/demonstrate.ts"),
        status: "added",
        language: asciiBytes("typescript"),
        diff: asciiBytes("diff --git a/src/demonstrate.ts b/src/demonstrate.ts\n--- a/src/demonstrate.ts\n+++ b/src/demonstrate.ts\n@@ -1,8 +1,12 @@\n+// typescript module: demonstrate.ts\n+export function generate() {\n+  return 94;\n+}"),
        additions: 5,
        deletions: 0,
        additionsLabel: asciiBytes("+5"),
        deletionsLabel: asciiBytes("-0"),
      },
      {
        id: 8,
        path: asciiBytes("src/components/gracefully_tarry.tsx"),
        status: "modified",
        language: asciiBytes("tsx"),
        diff: asciiBytes("diff --git a/src/components/gracefully_tarry.tsx b/src/components/gracefully_tarry.tsx\n--- a/src/components/gracefully_tarry.tsx\n+++ b/src/components/gracefully_tarry.tsx\n@@ -1,8 +1,12 @@\n import { hard drive } from \"./lib\";\n-const legacy = true;\n+const enabled = true;\n \n export function handle() {\n-  return legacy ? 0 : 1;\n+  return enabled ? 1 : 0;\n }"),
        additions: 10,
        deletions: 3,
        additionsLabel: asciiBytes("+10"),
        deletionsLabel: asciiBytes("-3"),
      }
        ] as const,
      },
      {
        id: 9,
        title: asciiBytes("Refactor alarm"),
        status: "running",
        statusLabel: asciiBytes("Running"),
        messages: [
      {
        id: 10,
        role: "user",
        isUser: true,
        content: asciiBytes("Add tests covering bandwidth selection state"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 13,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Possimus vulariter apud. Utpote talio subiungo subvenio contigo claudeo tolero. Usque vereor dolorem desipio theologus sol subvenio theatrum validus.\nCoruscus aliquid nesciunt adeptio deleniti. Cito officiis adaugeo adfero traho contigo antepono. Tepesco bibo qui ait admoneo excepturi hic."),
        toolCount: 2,
        tools: [
      {
        id: 11,
        name: asciiBytes("read_file"),
        state: "output_available",
        inputSummary: asciiBytes("read_file ha_oddball.deb"),
        outputSummary: asciiBytes("Celo careo voluptate crudelis vapulus."),
        errorText: asciiBytes(""),
      },
      {
        id: 12,
        name: asciiBytes("grep"),
        state: "output_error",
        inputSummary: asciiBytes("grep rarely_whoever.abw"),
        outputSummary: asciiBytes(""),
        errorText: asciiBytes("Vix ultio claustrum creo ullus comes assentator iusto video subito."),
      }
        ] as const,
      },
      {
        id: 14,
        role: "user",
        isUser: true,
        content: asciiBytes("Review the override digital system approach"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 15,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Carmen constans tempora accedo ancilla adipisci. Umbra succedo demitto. Deprimo demergo atavus.\nCubitum praesentium rem adipisci corrupti quidem. Umerus soluta ascisco aeneus sapiente acquiro occaecati. Necessitatibus cresco sed defungo in vilis creptio vito ventosus autus."),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 16,
        role: "user",
        isUser: true,
        content: asciiBytes("Add tests covering pixel selection state"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 17,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Tandem timor vulariter cupiditate. Tergeo confugo via una curto. Tego amet veniam despecto trepide comitatus vehemens creta abstergo."),
        toolCount: 0,
        tools: [

        ] as const,
      }
        ] as const,
        fileChanges: [

        ] as const,
      },
      {
        id: 18,
        title: asciiBytes("Agent: The VGA monitor is down, copy the optical port so we can bypass the AI firewall!"),
        status: "needs_review",
        statusLabel: asciiBytes("Review"),
        messages: [
      {
        id: 19,
        role: "user",
        isUser: true,
        content: asciiBytes("Fix the redundant bug in via_woot_cardboard.distz"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 21,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Sublime facilis collum torqueo stillicidium ascisco vere traho vir surgo. Cura vicissitudo usitas adipisci acquiro cotidie tollo. Arcus paens creator volubilis turbo tum delicate cuppedia certus adstringo.\nTorqueo xiphias vulnus itaque tenus vinco ulciscor carmen defendo. Virtus pecto calco spectaculum. Contabesco amplitudo speciosus eius ter eius ulterius."),
        toolCount: 1,
        tools: [
      {
        id: 20,
        name: asciiBytes("web_search"),
        state: "output_available",
        inputSummary: asciiBytes("web_search bench_quicker_irk.mpga"),
        outputSummary: asciiBytes("Audeo delectus conservo nulla aetas."),
        errorText: asciiBytes(""),
      }
        ] as const,
      },
      {
        id: 22,
        role: "user",
        isUser: true,
        content: asciiBytes("Add tests covering protocol selection state"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 23,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Deprimo causa degenero vomer depromo compono recusandae capto aestivus aperiam. Argentum aptus saepe attonbitus. Vel demitto sopor at aurum."),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 24,
        role: "user",
        isUser: true,
        content: asciiBytes("Add tests covering protocol selection state"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 25,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Timidus tamisium audacia bellum correptius. Quae corporis delectatio tametsi adfectus casus. Vehemens doloremque exercitationem amita dedecor expedita carcer censura."),
        toolCount: 0,
        tools: [

        ] as const,
      }
        ] as const,
        fileChanges: [
      {
        id: 26,
        path: asciiBytes("src/components/duh.ts"),
        status: "added",
        language: asciiBytes("typescript"),
        diff: asciiBytes("diff --git a/src/components/duh.ts b/src/components/duh.ts\n--- a/src/components/duh.ts\n+++ b/src/components/duh.ts\n@@ -1,8 +1,12 @@\n+// typescript module: duh.ts\n+export function index() {\n+  return 9;\n+}"),
        additions: 32,
        deletions: 0,
        additionsLabel: asciiBytes("+32"),
        deletionsLabel: asciiBytes("-0"),
      },
      {
        id: 27,
        path: asciiBytes("src/mock/middle_ferociously.tsx"),
        status: "modified",
        language: asciiBytes("tsx"),
        diff: asciiBytes("diff --git a/src/mock/middle_ferociously.tsx b/src/mock/middle_ferociously.tsx\n--- a/src/mock/middle_ferociously.tsx\n+++ b/src/mock/middle_ferociously.tsx\n@@ -1,8 +1,12 @@\n import { card } from \"./lib\";\n-const legacy = true;\n+const enabled = true;\n \n export function handle() {\n-  return legacy ? 0 : 1;\n+  return enabled ? 1 : 0;\n }"),
        additions: 7,
        deletions: 4,
        additionsLabel: asciiBytes("+7"),
        deletionsLabel: asciiBytes("-4"),
      }
        ] as const,
      },
      {
        id: 28,
        title: asciiBytes("Agent: I'll hack the back-end XML program, that should bus the VGA matrix!"),
        status: "failed",
        statusLabel: asciiBytes("Failed"),
        messages: [
      {
        id: 29,
        role: "user",
        isUser: true,
        content: asciiBytes("Review the quantify cross-platform panel approach"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 31,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Illum ventus quia angelus vigor quisquam. Apud thalassinus quam expedita varietas. Argentum color carpo tam ademptio molestiae tempus utor congregatio.\nAmor tyrannus antiquus crux thema architecto calculus suppono suppellex. Suasoria illo caste coniuratio attonbitus ver nostrum cui. Vinitor arguo occaecati dicta perferendis accusamus."),
        toolCount: 1,
        tools: [
      {
        id: 30,
        name: asciiBytes("run_terminal_command"),
        state: "output_available",
        inputSummary: asciiBytes("run_terminal_command boastfully_defiantly_imaginative.csv"),
        outputSummary: asciiBytes("Cotidie delectatio cogito tametsi desolo campana."),
        errorText: asciiBytes(""),
      }
        ] as const,
      }
        ] as const,
        fileChanges: [
      {
        id: 32,
        path: asciiBytes("lib/personalise_whisper_heighten.ts"),
        status: "added",
        language: asciiBytes("typescript"),
        diff: asciiBytes("diff --git a/lib/personalise_whisper_heighten.ts b/lib/personalise_whisper_heighten.ts\n--- a/lib/personalise_whisper_heighten.ts\n+++ b/lib/personalise_whisper_heighten.ts\n@@ -1,8 +1,12 @@\n+// typescript module: personalise_whisper_heighten.ts\n+export function generate() {\n+  return 80;\n+}"),
        additions: 3,
        deletions: 0,
        additionsLabel: asciiBytes("+3"),
        deletionsLabel: asciiBytes("-0"),
      },
      {
        id: 33,
        path: asciiBytes("src/kooky_unto.tsx"),
        status: "modified",
        language: asciiBytes("tsx"),
        diff: asciiBytes("diff --git a/src/kooky_unto.tsx b/src/kooky_unto.tsx\n--- a/src/kooky_unto.tsx\n+++ b/src/kooky_unto.tsx\n@@ -1,8 +1,12 @@\n import { monitor } from \"./lib\";\n-const legacy = true;\n+const enabled = true;\n \n export function handle() {\n-  return legacy ? 0 : 1;\n+  return enabled ? 1 : 0;\n }"),
        additions: 15,
        deletions: 15,
        additionsLabel: asciiBytes("+15"),
        deletionsLabel: asciiBytes("-15"),
      }
        ] as const,
      }
    ] as const,
  },
  {
    id: 34,
    name: asciiBytes("codex-shell-2"),
    path: asciiBytes("/Users/demo/Project/codex-shell-2"),
    description: asciiBytes("Digitized zero administration budgetary management"),
    threads: [
      {
        id: 35,
        title: asciiBytes("Agent: navigating the pixel won't do anything, we need to synthesize the bluetooth JSON application!"),
        status: "failed",
        statusLabel: asciiBytes("Failed"),
        messages: [
      {
        id: 36,
        role: "user",
        isUser: true,
        content: asciiBytes("Add tests covering array selection state"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 38,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Officia ceno quia cunae ipsam debeo. Vinum tenax apud ustilo depono. Thesaurus currus acerbitas censura id recusandae causa apud truculenter vorax."),
        toolCount: 1,
        tools: [
      {
        id: 37,
        name: asciiBytes("grep"),
        state: "output_available",
        inputSummary: asciiBytes("grep downright.xls"),
        outputSummary: asciiBytes("Abundans ait beatus acquiro attonbitus nostrum curis vapulus totidem congregatio."),
        errorText: asciiBytes(""),
      }
        ] as const,
      },
      {
        id: 39,
        role: "user",
        isUser: true,
        content: asciiBytes("Review the back up back-end sensor approach"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 40,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Atque vergo curatio crebro earum adipiscor aspernatur taceo. Pax cariosus creta. Constans super clibanus maxime demonstro.\nVideo synagoga bestia addo celebrer pariatur admoneo derelinquo. Concido tepidus amissio aestivus suscipit deputo sto. Caritas totus thermae sub cernuus officia."),
        toolCount: 0,
        tools: [

        ] as const,
      }
        ] as const,
        fileChanges: [

        ] as const,
      },
      {
        id: 41,
        title: asciiBytes("Agent: transmitting the bus won't do anything, we need to reboot the redundant SMTP capacitor!"),
        status: "completed",
        statusLabel: asciiBytes("Done"),
        messages: [
      {
        id: 42,
        role: "user",
        isUser: true,
        content: asciiBytes("Implement navigate for sensor"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 45,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Sodalitas pecus dolores callide atqui bos audentia tergum consectetur adsuesco. Vacuus vestigium vulgus atavus crustulum tempora subito arguo totam caelestis. Fuga optio nisi aliqua."),
        toolCount: 2,
        tools: [
      {
        id: 43,
        name: asciiBytes("read_file"),
        state: "output_error",
        inputSummary: asciiBytes("read_file meh_what.pdf"),
        outputSummary: asciiBytes(""),
        errorText: asciiBytes("Conspergo cito clibanus."),
      },
      {
        id: 44,
        name: asciiBytes("search_replace"),
        state: "output_available",
        inputSummary: asciiBytes("search_replace ack.buffer"),
        outputSummary: asciiBytes("Utroque vinco deleo placeat aspernatur vulgaris."),
        errorText: asciiBytes(""),
      }
        ] as const,
      },
      {
        id: 46,
        role: "user",
        isUser: true,
        content: asciiBytes("Review the navigate cross-platform sensor approach"),
        toolCount: 0,
        tools: [

        ] as const,
      }
        ] as const,
        fileChanges: [
      {
        id: 47,
        path: asciiBytes("lib/cumbersome_sleepily_pixellate.ts"),
        status: "added",
        language: asciiBytes("typescript"),
        diff: asciiBytes("diff --git a/lib/cumbersome_sleepily_pixellate.ts b/lib/cumbersome_sleepily_pixellate.ts\n--- a/lib/cumbersome_sleepily_pixellate.ts\n+++ b/lib/cumbersome_sleepily_pixellate.ts\n@@ -1,8 +1,12 @@\n+// typescript module: cumbersome_sleepily_pixellate.ts\n+export function override() {\n+  return 26;\n+}"),
        additions: 40,
        deletions: 0,
        additionsLabel: asciiBytes("+40"),
        deletionsLabel: asciiBytes("-0"),
      },
      {
        id: 48,
        path: asciiBytes("src/mock/quietly_seemingly.tsx"),
        status: "modified",
        language: asciiBytes("tsx"),
        diff: asciiBytes("diff --git a/src/mock/quietly_seemingly.tsx b/src/mock/quietly_seemingly.tsx\n--- a/src/mock/quietly_seemingly.tsx\n+++ b/src/mock/quietly_seemingly.tsx\n@@ -1,8 +1,12 @@\n import { driver } from \"./lib\";\n-const legacy = true;\n+const enabled = true;\n \n export function handle() {\n-  return legacy ? 0 : 1;\n+  return enabled ? 1 : 0;\n }"),
        additions: 3,
        deletions: 15,
        additionsLabel: asciiBytes("+3"),
        deletionsLabel: asciiBytes("-15"),
      }
        ] as const,
      },
      {
        id: 49,
        title: asciiBytes("Agent: You can't transmit the bandwidth without backing up the digital SSL firewall!"),
        status: "idle",
        statusLabel: asciiBytes("Idle"),
        messages: [
      {
        id: 50,
        role: "user",
        isUser: true,
        content: asciiBytes("Implement bypass for panel"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 52,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Claro sub undique termes adflicto denique amicitia. Vos aranea deserunt quae. Laborum absque compello eaque alias consequatur ademptio aeternus."),
        toolCount: 1,
        tools: [
      {
        id: 51,
        name: asciiBytes("grep"),
        state: "output_available",
        inputSummary: asciiBytes("grep starboard_sham_make.dot"),
        outputSummary: asciiBytes("Censura thema colo deficio absum aequus crudelis."),
        errorText: asciiBytes(""),
      }
        ] as const,
      },
      {
        id: 53,
        role: "user",
        isUser: true,
        content: asciiBytes("Implement hack for bandwidth"),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 54,
        role: "assistant",
        isUser: false,
        content: asciiBytes("Blanditiis voluptates conduco attonbitus testimonium soluta deripio itaque super. Vulnus voluptatem sol aveho. Aequus adaugeo causa delectatio ustilo suscipio talis cursim."),
        toolCount: 0,
        tools: [

        ] as const,
      },
      {
        id: 55,
        role: "user",
        isUser: true,
        content: asciiBytes("Review the connect online sensor approach"),
        toolCount: 0,
        tools: [

        ] as const,
      }
        ] as const,
        fileChanges: [

        ] as const,
      }
    ] as const,
  }
] as const;
