//! Lucide static icon registry for Native SDK.
//!
//! Generated by `scripts/sync-lucide-icons.mjs` from `lucide-static`.
//! Do not hand-edit the parsed SVG bodies — change ICON_NAMES in the
//! script and re-run. Markup references: `app:<name>` (e.g. app:folder).
//!
//! @see https://lucide.dev/guide/static/
//! @see https://lucide.dev/icons/

const native_sdk = @import("native_sdk");
const canvas = native_sdk.canvas;

const alert_circle = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="12" cy="12" r="10" />
    \\  <line x1="12" x2="12" y1="8" y2="12" />
    \\  <line x1="12" x2="12.01" y1="16" y2="16" />
    \\</svg>
);

const arrow_up = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m5 12 7-7 7 7" />
    \\  <path d="M12 19V5" />
    \\</svg>
);

const bot = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M12 8V4H8" />
    \\  <rect width="16" height="12" x="4" y="8" rx="2" />
    \\  <path d="M2 14h2" />
    \\  <path d="M20 14h2" />
    \\  <path d="M15 13v2" />
    \\  <path d="M9 13v2" />
    \\</svg>
);

const check = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M20 6 9 17l-5-5" />
    \\</svg>
);

const check_circle = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M21.801 10A10 10 0 1 1 17 3.335" />
    \\  <path d="m9 11 3 3L22 4" />
    \\</svg>
);

const chevron_down = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m6 9 6 6 6-6" />
    \\</svg>
);

const chevron_right = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m9 18 6-6-6-6" />
    \\</svg>
);

const code = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m16 18 6-6-6-6" />
    \\  <path d="m8 6-6 6 6 6" />
    \\</svg>
);

const copy = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
    \\  <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    \\</svg>
);

const diff = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M12 3v14" />
    \\  <path d="M5 10h14" />
    \\  <path d="M5 21h14" />
    \\</svg>
);

const ellipsis = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="12" cy="12" r="1" />
    \\  <circle cx="19" cy="12" r="1" />
    \\  <circle cx="5" cy="12" r="1" />
    \\</svg>
);

const external_link = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M15 3h6v6" />
    \\  <path d="M10 14 21 3" />
    \\  <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
    \\</svg>
);

const file_code = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />
    \\  <path d="M14 2v5a1 1 0 0 0 1 1h5" />
    \\  <path d="M10 12.5 8 15l2 2.5" />
    \\  <path d="m14 12.5 2 2.5-2 2.5" />
    \\</svg>
);

const file_text = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z" />
    \\  <path d="M14 2v5a1 1 0 0 0 1 1h5" />
    \\  <path d="M10 9H8" />
    \\  <path d="M16 13H8" />
    \\  <path d="M16 17H8" />
    \\</svg>
);

const folder = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    \\</svg>
);

const folder_open = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />
    \\</svg>
);

const git_branch = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M15 6a9 9 0 0 0-9 9V3" />
    \\  <circle cx="18" cy="6" r="3" />
    \\  <circle cx="6" cy="18" r="3" />
    \\</svg>
);

const git_pull_request = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="18" cy="18" r="3" />
    \\  <circle cx="6" cy="6" r="3" />
    \\  <path d="M13 6h3a2 2 0 0 1 2 2v7" />
    \\  <line x1="6" x2="6" y1="9" y2="21" />
    \\</svg>
);

const info = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="12" cy="12" r="10" />
    \\  <path d="M12 16v-4" />
    \\  <path d="M12 8h.01" />
    \\</svg>
);

const loader_circle = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    \\</svg>
);

const message_square = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" />
    \\</svg>
);

const mic = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M12 19v3" />
    \\  <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
    \\  <rect x="9" y="2" width="6" height="13" rx="3" />
    \\</svg>
);

const monitor = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <rect width="20" height="14" x="2" y="3" rx="2" />
    \\  <line x1="8" x2="16" y1="21" y2="21" />
    \\  <line x1="12" x2="12" y1="17" y2="21" />
    \\</svg>
);

const moon = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />
    \\</svg>
);

const panel_left = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <rect width="18" height="18" x="3" y="3" rx="2" />
    \\  <path d="M9 3v18" />
    \\</svg>
);

const paperclip = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" />
    \\</svg>
);

const play = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z" />
    \\</svg>
);

const plus = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M5 12h14" />
    \\  <path d="M12 5v14" />
    \\</svg>
);

const refresh_cw = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
    \\  <path d="M21 3v5h-5" />
    \\  <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
    \\  <path d="M8 16H3v5" />
    \\</svg>
);

const search = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="m21 21-4.34-4.34" />
    \\  <circle cx="11" cy="11" r="8" />
    \\</svg>
);

const send = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
    \\  <path d="m21.854 2.147-10.94 10.939" />
    \\</svg>
);

const settings = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" />
    \\  <circle cx="12" cy="12" r="3" />
    \\</svg>
);

const sparkles = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" />
    \\  <path d="M20 2v4" />
    \\  <path d="M22 4h-4" />
    \\  <circle cx="4" cy="20" r="2" />
    \\</svg>
);

const square = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <rect width="18" height="18" x="3" y="3" rx="2" />
    \\</svg>
);

const sun = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="12" cy="12" r="4" />
    \\  <path d="M12 2v2" />
    \\  <path d="M12 20v2" />
    \\  <path d="m4.93 4.93 1.41 1.41" />
    \\  <path d="m17.66 17.66 1.41 1.41" />
    \\  <path d="M2 12h2" />
    \\  <path d="M20 12h2" />
    \\  <path d="m6.34 17.66-1.41 1.41" />
    \\  <path d="m19.07 4.93-1.41 1.41" />
    \\</svg>
);

const terminal = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M12 19h8" />
    \\  <path d="m4 17 6-6-6-6" />
    \\</svg>
);

const trash_2 = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M10 11v6" />
    \\  <path d="M14 11v6" />
    \\  <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
    \\  <path d="M3 6h18" />
    \\  <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
    \\</svg>
);

const x = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <path d="M18 6 6 18" />
    \\  <path d="m6 6 12 12" />
    \\</svg>
);

const x_circle = canvas.svg_icon.parseComptime(
    \\<svg
    \\  xmlns="http://www.w3.org/2000/svg"
    \\  width="24"
    \\  height="24"
    \\  viewBox="0 0 24 24"
    \\  fill="none"
    \\  stroke="currentColor"
    \\  stroke-width="2"
    \\  stroke-linecap="round"
    \\  stroke-linejoin="round"
    \\>
    \\  <circle cx="12" cy="12" r="10" />
    \\  <path d="m15 9-6 6" />
    \\  <path d="m9 9 6 6" />
    \\</svg>
);

/// Same table handed to `canvas.icons.registerAppIcons` and exposed as
/// `pub const app_icons` on the app root for `native check`.
pub const app_icons = [_]canvas.icons.Entry{
    .{ .name = "alert-circle", .icon = &alert_circle },
    .{ .name = "arrow-up", .icon = &arrow_up },
    .{ .name = "bot", .icon = &bot },
    .{ .name = "check", .icon = &check },
    .{ .name = "check-circle", .icon = &check_circle },
    .{ .name = "chevron-down", .icon = &chevron_down },
    .{ .name = "chevron-right", .icon = &chevron_right },
    .{ .name = "code", .icon = &code },
    .{ .name = "copy", .icon = &copy },
    .{ .name = "diff", .icon = &diff },
    .{ .name = "ellipsis", .icon = &ellipsis },
    .{ .name = "external-link", .icon = &external_link },
    .{ .name = "file-code", .icon = &file_code },
    .{ .name = "file-text", .icon = &file_text },
    .{ .name = "folder", .icon = &folder },
    .{ .name = "folder-open", .icon = &folder_open },
    .{ .name = "git-branch", .icon = &git_branch },
    .{ .name = "git-pull-request", .icon = &git_pull_request },
    .{ .name = "info", .icon = &info },
    .{ .name = "loader-circle", .icon = &loader_circle },
    .{ .name = "message-square", .icon = &message_square },
    .{ .name = "mic", .icon = &mic },
    .{ .name = "monitor", .icon = &monitor },
    .{ .name = "moon", .icon = &moon },
    .{ .name = "panel-left", .icon = &panel_left },
    .{ .name = "paperclip", .icon = &paperclip },
    .{ .name = "play", .icon = &play },
    .{ .name = "plus", .icon = &plus },
    .{ .name = "refresh-cw", .icon = &refresh_cw },
    .{ .name = "search", .icon = &search },
    .{ .name = "send", .icon = &send },
    .{ .name = "settings", .icon = &settings },
    .{ .name = "sparkles", .icon = &sparkles },
    .{ .name = "square", .icon = &square },
    .{ .name = "sun", .icon = &sun },
    .{ .name = "terminal", .icon = &terminal },
    .{ .name = "trash-2", .icon = &trash_2 },
    .{ .name = "x", .icon = &x },
    .{ .name = "x-circle", .icon = &x_circle },
};

pub fn register() void {
    canvas.icons.registerAppIcons(&app_icons);
}
